### ISSUE TITLE
Manage the app from an iPhone

### ISSUE THREAD

**Issue by AndresVeraCacho** [AndresVeraCacho/GESPRO_Practica_2_Curso_2024_2025#13]

**Comment by AndresVeraCacho** [comment]
Arkaitz, tengo algunas dudas que quiero aclarar antes de seguir adelante. ¿Debe la interfaz ser completamente adaptada para iOS, o podemos trabajar con una versión web optimizada para dispositivos móviles?

**Comment by adg1034** [comment]
Hola Andres!
Podemos empezar con una versión web optimizada para dispositivos móviles, que sea funcional y rápida. Así cubrimos un rango más amplio de usuarios y luego vemos si vale la pena invertir en una adaptación completa para iOS según el feedback.
