### ISSUE TITLE
Transfer money

### ISSUE THREAD

**Issue by AndresVeraCacho** [AndresVeraCacho/GESPRO_Practica_2_Curso_2024_2025#16]

**Comment by adg1034** [comment]
Hola mi gran amigo Pablo, tengo una duda inmensa respecto al proyecto ¿Qué métodos o endpoints específicos deberíamos implementar para manejar la transferencia de dinero de forma segura en el flujo actual del proyecto?

**Comment by pabloVelascoMR** [comment]
Hola Arkaitz, Implementa endpoints para autenticación, transferencia, confirmación, verificación de estado y auditoría, asegurando encriptación, autenticación multifactor y cumplimiento normativo.
