### ISSUE TITLE
Manage accounts

### ISSUE THREAD

**Issue by AndresVeraCacho** [AndresVeraCacho/GESPRO_Practica_2_Curso_2024_2025#22]

**Comment by AndresVeraCacho** [comment]
¿Involucra creación, actualización, eliminación de cuentas o configuración de permisos y roles?

**Comment by pabloVelascoMR** [comment]
Sí claro, implica la gestión de cuentas de usuario, lo que incluye la creación de nuevas cuentas, la actualización de las existentes (como modificar datos o permisos), y la eliminación de cuentas que ya no sean necesarias. Además, también abarca la configuración de permisos y roles, lo cual define qué acciones o recursos puede acceder cada usuario dentro de un sistema, asegurando así una administración adecuada y segura de los recursos.

**Comment by AndresVeraCacho** [comment]
Muchas gracias

**Comment by pabloVelascoMR** [comment]
Nada, cualquier otra cosa me comentas 💪
