### ISSUE TITLE
Monitor currency rate

### ISSUE THREAD

**Issue by AndresVeraCacho** [AndresVeraCacho/GESPRO_Practica_2_Curso_2024_2025#33]

**Comment by pabloVelascoMR** [comment]
Hola, qué métodos o tecnologías podríamos utilizar para monitorear y actualizar de manera precisa y en tiempo real las tasas de cambio de divisas en nuestra aplicación?

**Comment by adg1034** [comment]
Hola! que pregunta mas buena! Podríamos utilizar APIs como Fixer.io o Open Exchange Rates para obtener las tasas en tiempo real, junto con WebSockets para mantener las actualizaciones constantes en la app. También podemos implementar una base de datos en memoria como Redis para mejorar el rendimiento y asegurarnos de que los datos sean accesibles rápidamente
